# This is a basic workflow to help you get started with Actions

name: Build-and-Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  # checkout all sources from git
      - name: Checkout Sources
        uses: actions/checkout@v2
    # install dotnet SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
  # restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore
  # build the project
      - name: Build
        run: dotnet build --no-restore
  # run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal
